#!/bin/bash
#on commence par supprimer les anciennes config de IP sur les postes afin
# de faire la demande au près du serveur DHCP
#poste1
ip netns exec poste1 ip a del 192.168.100.1/24 dev poste1-eth0.100
ip netns exec poste1 dhclient poste1-eth0.100
#on supprime la route par défaut aussi

#poste3
ip netns exec poste3 ip a del 192.168.100.2/24 dev poste3-eth0.100
ip netns exec poste3 dhclient poste3-eth0.100

#poste2
ip netns exec poste2 ip a del 192.168.200.1/24 dev poste2-eth0.200
ip netns exec poste2 dhclient poste2-eth0.200
 
#poste4
ip netns exec poste4 ip a del 192.168.200.2/24 dev poste4-eth0.200
ip netns exec poste4 dhclient poste4-eth0.200

