#!/bin/bash

#pour créer des vlans sur un routeur(rout1 et 2), on doit ajouter les sous ports aux 
#interfaces qui possèdent pas de congi ip(rout1-eth1 pour rout1)
#ce sont ces sous interfaces qui auront des adresses ip
#ajout sous interface rout1-eth1.100 pour vlan 100
#routeur 1
ip netns exec rout1 ip link add link rout1-eth1 name rout1-eth1.100 type vlan id 100
ip netns exec rout1 ip link add link rout1-eth1 name rout1-eth1.200 type vlan id 200
#up des nuvelles interfaces
ip netns exec rout1 ip link set dev rout1-eth1.100 up
ip netns exec rout1 ip link set dev rout1-eth1.200 up

#attribution d'adresses aux nouvelles interface
ip netns exec rout1 ip a add 192.168.100.254/24 dev rout1-eth1.100
ip netns exec rout1 ip a add 192.168.200.254/24 dev rout1-eth1.200


#routeur 2
ip netns exec rout2 ip link add link rout2-eth1 name rout2-eth1.100 type vlan id 100
ip netns exec rout2 ip link add link rout2-eth1 name rout2-eth1.200 type vlan id 200

#up des nuvelles interfaces
ip netns exec rout2 ip link set dev rout2-eth1.100 up
ip netns exec rout2 ip link set dev rout2-eth1.200 up

#attribution d'adresses aux nouvelles interface
ip netns exec rout2 ip a add 192.168.100.253/24 dev rout2-eth1.100
ip netns exec rout2 ip a add 192.168.200.253/24 dev rout2-eth1.200

#De même, il faut ajouter des postes dans des vlans adequats

#poste1
ip netns exec poste1 ip a del 192.168.100.1/24 dev poste1-eth0 #supprime la config initiale
ip netns exec poste1 ip link add link poste1-eth0 name poste1-eth0.100 type vlan id 100
ip netns exec poste1 ip link set dev poste1-eth0.100 up
ip netns exec poste1 ip a add 192.168.100.1/24 brd 192.168.100.255 dev poste1-eth0.100
ip netns exec poste1 ip r add default via 192.168.100.253

#poste2
ip netns exec poste2 ip a del 192.168.200.1/24 dev poste2-eth0 #supprime la config initiale
ip netns exec poste2 ip link add link poste2-eth0 name poste2-eth0.200 type vlan id 200
ip netns exec poste2 ip link set dev poste2-eth0.200 up
ip netns exec poste2 ip a add 192.168.200.1/24 brd 192.168.200.255 dev poste2-eth0.200
ip netns exec poste2 ip r add default via  192.168.200.253

#poste3
ip netns exec poste3 ip a del 192.168.100.2/24 dev poste3-eth0 #supprime la config initiale
ip netns exec poste3 ip link add link poste3-eth0 name poste3-eth0.100 type vlan id 100
ip netns exec poste3 ip link set dev poste3-eth0.100 up
ip netns exec poste3 ip a add 192.168.100.2/24 brd 192.168.100.255 dev poste3-eth0.100
ip netns exec poste3 ip r add default via 192.168.100.254

#poste4
ip netns exec poste4 ip a del 192.168.200.2/24 dev poste4-eth0 #supprime la config initiale
ip netns exec poste4 ip link add link poste4-eth0 name poste4-eth0.200 type vlan id 200
ip netns exec poste4 ip link set dev poste4-eth0.200 up
ip netns exec poste4 ip a add 192.168.200.2/24 brd 192.168.200.255 dev poste4-eth0.200
ip netns exec poste4 ip r add default via 192.168.200.254